updatedyml

diff --git a/.github/workflows/ant.yml b/.github/workflows/ant.yml
--- a/.github/workflows/ant.yml
+++ b/.github/workflows/ant.yml
@@ -1,6 +1,3 @@
-# This workflow will build a Java project with Ant
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
-
 name: Java CI
 
 on:
@@ -17,24 +14,22 @@ jobs:
       PROJECT_DIR: ${{ github.workspace }}
 
     steps:
-      # Checkout source code
       - uses: actions/checkout@v4
 
-      # Set up JDK 21
       - name: Set up JDK 21
         uses: actions/setup-java@v4
         with:
           java-version: '21'
           distribution: 'temurin'
+
       - name: Check HTTPS connectivity
         run: |
-         URL="https://prod.provar.cloud/artifactory/artifactory/"
-         echo "Checking HTTPS connectivity to: $URL"
-         echo "Timestamp: $(date)"
-         curl -IL --connect-timeout 10 "$URL" || echo " Unable to reach $URL"
-         echo "Connectivity test completed at $(date)"
-         
-      # Run Ant build
+          URL="https://prod.provar.cloud/artifactory/artifactory/"
+          echo "Checking HTTPS connectivity to: $URL"
+          echo "Timestamp: $(date)"
+          curl -IL --connect-timeout 10 "$URL" || echo " Unable to reach $URL"
+          echo "Connectivity test completed at $(date)"
+
       - name: Build with Ant
         run: |
           mkdir $GITHUB_WORKSPACE/ProvarHome
@@ -49,21 +44,24 @@ jobs:
           sudo apt-get install -y firefox
           echo $PROVAR_HOME
           echo $PROJECT_DIR
-          xvfb-run ant -f $PROJECT_DIR/ANT/build.xml
-          du -sh "$HOME/Provar/.nitroX"
+          xvfb-run ant -v -f $PROJECT_DIR/ANT/build.xml
+          du -sh "$HOME/Provar/.nitroX" || true
 
-      # Upload artifacts
-      - uses: actions/upload-artifact@v4
+      - name: Upload Execution Report
+        uses: actions/upload-artifact@v4
         with:
           name: Execution Report
           path: ${{ env.PROJECT_DIR }}/ANT/Results/*
-       # Upload nitrox artifacts
-      - uses: actions/upload-artifact@v4
+
+      - name: Upload Nitrox Logs
+        uses: actions/upload-artifact@v4
         with:
           name: NitroxLogs
-          path: ${{ github.workspace }}/.provarCaches 
-      - uses: actions/upload-artifact@v4
+          path: ${{ github.workspace }}/.provarCaches
+
+      - name: Upload Execution Report (Failed)
         if: failure()
+        uses: actions/upload-artifact@v4
         with:
           name: Execution Report (Failed)
           path: ${{ env.PROJECT_DIR }}/ANT/Results/*
